# Generated by Django 6.0.2 on 2026-02-26 11:47

import django.db.models.deletion
import django_mongodb_backend.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full legal name used for verification', max_length=255)),
                ('age', models.PositiveIntegerField(help_text='Current age of the child')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('location', models.CharField(help_text='Specific area or address', max_length=255)),
                ('biography', models.TextField(help_text='Personal background and life story')),
                ('vulnerability_status', models.CharField(help_text='e.g., street child, orphan', max_length=255)),
                ('guardian_info', models.TextField(help_text='Name and contact details of the legal guardian')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='children/photos/')),
                ('supporting_docs', models.FileField(blank=True, null=True, upload_to='children/documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Waiting for Admin)'), ('PUBLISHED', 'Published (Visible to Sponsors)'), ('SPONSORED', 'Sponsored (Fully supported)'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(help_text='The NGO or Orphanage staff who registered this child', on_delete=django.db.models.deletion.CASCADE, related_name='registered_children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Child Profile',
                'verbose_name_plural': 'Child Profiles',
            },
        ),
        migrations.CreateModel(
            name='InterventionLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HEALTH', 'Healthcare'), ('EDUCATION', 'Education'), ('NUTRITION', 'Nutrition'), ('CLOTHING', 'Clothing/Shelter')], max_length=50)),
                ('description', models.TextField()),
                ('date_provided', models.DateField()),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='interventions/receipts/')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='childprofile.childprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('commitment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='childprofile.childprofile')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
