# Generated by Django 6.0.3 on 2026-03-20 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('grade_level', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Enrollment'), ('ENROLLED', 'Currently Enrolled'), ('GRADUATED', 'Graduated'), ('DROPPED', 'Dropped Out')], default='ENROLLED', max_length=20)),
                ('enrollment_number', models.CharField(max_length=100, unique=True)),
                ('class_section', models.CharField(blank=True, max_length=50)),
                ('enrollment_document', models.FileField(blank=True, null=True, upload_to='enrollments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('PROFILE_APPROVED', 'Profile Approved'), ('PROFILE_REJECTED', 'Profile Rejected'), ('SPONSORED', 'Child Sponsored'), ('INTERVENTION_ADDED', 'Intervention Added'), ('REPORT_SUBMITTED', 'Report Submitted'), ('STATUS_UPDATED', 'Status Updated')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildProgressReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_progress', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('SATISFACTORY', 'Satisfactory'), ('NEEDS_IMPROVEMENT', 'Needs Improvement')], max_length=20)),
                ('attendance_progress', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('SATISFACTORY', 'Satisfactory'), ('NEEDS_IMPROVEMENT', 'Needs Improvement')], max_length=20)),
                ('behavior_progress', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('SATISFACTORY', 'Satisfactory'), ('NEEDS_IMPROVEMENT', 'Needs Improvement')], max_length=20)),
                ('overall_progress', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('SATISFACTORY', 'Satisfactory'), ('NEEDS_IMPROVEMENT', 'Needs Improvement')], max_length=20)),
                ('summary', models.TextField()),
                ('recommendations', models.TextField()),
                ('report_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DuplicationAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField()),
                ('matching_fields', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed Duplicate'), ('FALSE_POSITIVE', 'False Positive'), ('MERGED', 'Merged'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('SPONSORSHIP_AGREEMENT', 'Sponsorship Agreement'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('BANK_STATEMENT', 'Bank Statement'), ('INVOICE', 'Invoice'), ('REPORT', 'Financial Report')], max_length=50)),
                ('document_file', models.FileField(upload_to='financial_documents/')),
                ('document_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_date', models.DateField(unique=True)),
                ('total_children_registered', models.IntegerField(default=0)),
                ('total_children_sponsored', models.IntegerField(default=0)),
                ('total_children_unsponsored', models.IntegerField(default=0)),
                ('total_sponsorships', models.IntegerField(default=0)),
                ('active_sponsorships', models.IntegerField(default=0)),
                ('total_commitment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_interventions', models.IntegerField(default=0)),
                ('health_interventions', models.IntegerField(default=0)),
                ('education_interventions', models.IntegerField(default=0)),
                ('nutrition_interventions', models.IntegerField(default=0)),
                ('clothing_interventions', models.IntegerField(default=0)),
                ('average_attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_organizations', models.IntegerField(default=0)),
                ('active_organizations', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_sponsors', models.IntegerField(default=0)),
                ('total_schools', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-metric_date'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('USER_ACTION', 'User Action'), ('SYSTEM_EVENT', 'System Event'), ('ERROR', 'Error'), ('SECURITY', 'Security Event')], max_length=50)),
                ('action', models.CharField(max_length=255)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='childprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionlog',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship', to='childprofile.childprofile'),
        ),
        migrations.AddIndex(
            model_name='interventionlog',
            index=models.Index(fields=['date_provided'], name='childprofil_date_pr_d686b5_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorship',
            index=models.Index(fields=['sponsor', 'is_active'], name='childprofil_sponsor_5f7880_idx'),
        ),
        migrations.AddField(
            model_name='childenrollment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='childprofile.childprofile'),
        ),
        migrations.AddField(
            model_name='childenrollment',
            name='school',
            field=models.ForeignKey(limit_choices_to={'role': 'SCHOOL'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childnotification',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='childprofile.childprofile'),
        ),
        migrations.AddField(
            model_name='childnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childprogressreport',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='childprofile.childprofile'),
        ),
        migrations.AddField(
            model_name='childprogressreport',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duplicationalert',
            name='duplicate_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplication_alerts_duplicate', to='childprofile.childprofile'),
        ),
        migrations.AddField(
            model_name='duplicationalert',
            name='primary_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplication_alerts_primary', to='childprofile.childprofile'),
        ),
        migrations.AddField(
            model_name='duplicationalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_duplications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_financial_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialdocument',
            name='sponsorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_documents', to='childprofile.sponsorship'),
        ),
        migrations.AddIndex(
            model_name='programmetrics',
            index=models.Index(fields=['metric_date'], name='childprofil_metric__39b391_idx'),
        ),
        migrations.AddField(
            model_name='sponsorshippayment',
            name='sponsorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='childprofile.sponsorship'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='childenrollment',
            index=models.Index(fields=['child', 'status'], name='childprofil_child_i_135eed_idx'),
        ),
        migrations.AddIndex(
            model_name='childenrollment',
            index=models.Index(fields=['school'], name='childprofil_school__f33852_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='childenrollment',
            unique_together={('child', 'school', 'enrollment_date')},
        ),
        migrations.AddIndex(
            model_name='childnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='childprofil_recipie_95b80d_idx'),
        ),
        migrations.AddIndex(
            model_name='childnotification',
            index=models.Index(fields=['created_at'], name='childprofil_created_fe239f_idx'),
        ),
        migrations.AddIndex(
            model_name='childprogressreport',
            index=models.Index(fields=['child', 'report_date'], name='childprofil_child_i_5f88a8_idx'),
        ),
        migrations.AddIndex(
            model_name='duplicationalert',
            index=models.Index(fields=['status'], name='childprofil_status_efc1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='duplicationalert',
            index=models.Index(fields=['created_at'], name='childprofil_created_c8c0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='financialdocument',
            index=models.Index(fields=['sponsorship', 'status'], name='childprofil_sponsor_838d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='financialdocument',
            index=models.Index(fields=['document_date'], name='childprofil_documen_0f9163_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorshippayment',
            index=models.Index(fields=['sponsorship', 'payment_date'], name='childprofil_sponsor_9c6c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorshippayment',
            index=models.Index(fields=['status'], name='childprofil_status_2377ff_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['user', 'created_at'], name='childprofil_user_id_6436bb_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['log_type'], name='childprofil_log_typ_9c5870_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['created_at'], name='childprofil_created_cd78ce_idx'),
        ),
    ]
