# Generated by Django 6.0.3 on 2026-03-21 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childprofile', '0002_childenrollment_childnotification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='sponsorships/proofs/'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('TELEBIRR', 'Telebirr'), ('CBE', 'Commercial Bank of Ethiopia'), ('BANK', 'Other Bank Transfer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Manual Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sponsorships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='childnotification',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='childprofile.childprofile'),
        ),
        migrations.AlterField(
            model_name='childnotification',
            name='notification_type',
            field=models.CharField(choices=[('PROFILE_APPROVED', 'Profile Approved'), ('PROFILE_REJECTED', 'Profile Rejected'), ('SPONSORED', 'Child Sponsored'), ('INTERVENTION_ADDED', 'Intervention Added'), ('REPORT_SUBMITTED', 'Report Submitted'), ('STATUS_UPDATED', 'Status Updated'), ('USER_REGISTERED', 'User Registered'), ('ACCOUNT_APPROVED', 'Account Approved'), ('ACCOUNT_REJECTED', 'Account Rejected'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('ORG_CREATED', 'Organization Created'), ('ORG_APPROVED', 'Organization Approved'), ('ORG_REJECTED', 'Organization Rejected'), ('SCHOOL_PROFILE_CREATED', 'School Profile Created'), ('SCHOOL_PROFILE_UPDATED', 'School Profile Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
