# Generated by Django 6.0.3 on 2026-03-20 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('childprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('ORPHANAGE', 'Orphanage'), ('NGO', 'Non-Governmental Organization'), ('RELIGIOUS', 'Religion Based Institution'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='org_documents/licenses/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_documents/logos/')),
                ('description', models.TextField(blank=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_organizations', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'ORG_STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildSubmissionTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted'), ('PUBLISHED', 'Published')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_tracking', to='childprofile.childprofile')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_tracking', to='organization.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], max_length=20)),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('sponsored_count', models.PositiveIntegerField(default=0)),
                ('interventions_count', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField()),
                ('challenges', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='org_reports/')),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organization.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_org_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_org_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipReceived',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_sponsorships', to='organization.organization')),
                ('sponsorship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_notification', to='childprofile.sponsorship')),
            ],
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status', 'org_type'], name='organizatio_status_5cf3a7_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['owner'], name='organizatio_owner_i_8d2c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='childsubmissiontracking',
            index=models.Index(fields=['child', 'action'], name='organizatio_child_i_73acec_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationreport',
            index=models.Index(fields=['organization', 'report_date'], name='organizatio_organiz_87e42f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationreport',
            index=models.Index(fields=['status'], name='organizatio_status_5023e2_idx'),
        ),
    ]
