# Generated by Django 6.0.2 on 2026-02-26 12:27

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('childprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicReport',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(help_text='e.g., 2016 E.C', max_length=20)),
                ('term', models.CharField(choices=[('TERM_1', 'First Term'), ('TERM_2', 'Second Term'), ('ANNUAL', 'Annual Result')], max_length=20)),
                ('grade_level', models.CharField(help_text='e.g., Grade 5', max_length=50)),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_rate', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('report_card_image', models.ImageField(blank=True, null=True, upload_to='academic_reports/')),
                ('teacher_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_reports', to='childprofile.childprofile')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
