# Generated by Django 6.0.3 on 2026-03-20 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadamicreport', '0001_initial'),
        ('childprofile', '0002_childenrollment_childnotification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='academicreport',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='academicreport',
            unique_together={('child', 'academic_year', 'term')},
        ),
        migrations.AddIndex(
            model_name='academicreport',
            index=models.Index(fields=['child', 'academic_year'], name='acadamicrep_child_i_719550_idx'),
        ),
        migrations.AddIndex(
            model_name='academicreport',
            index=models.Index(fields=['reported_by'], name='acadamicrep_reporte_129ec8_idx'),
        ),
    ]
